### ISSUE TITLE
Allow review apps to be created for PR's originating from forks

### ISSUE THREAD

**Issue by KevinMulhern** [fastruby/create-heroku-review-app#2]
Thank you for this great utility, it's been a huge time saver for us at The Odin Project.

I was wondering if it would be safe or possible to remove the restriction on PR's from forks? 

With only team members being able to apply labels on GitHub, it appears to be safe on the surface to me. But I could absolutely be missing something obvious, is there anything I'm not considering?

**Comment by etagwerker** [comment]
@KevinMulhern I don't see any issues with that. What do you think, @arielj?

**Comment by KevinMulhern** [comment]
Friendly bump 😄

**Comment by etagwerker** [comment]
@KevinMulhern Thanks for the reminder! I just submitted #3. Waiting for @arielj to review.

**Comment by KevinMulhern** [comment]
Thanks so much @etagwerker 💪  and thanks again for such a great tool!

**Comment by etagwerker** [comment]
@KevinMulhern Thanks for submitting this issue! Until this issue was submitted @arielj and I had no idea anybody else would find it useful. 😂

**Comment by arielj** [comment]
@KevinMulhern you should be able to update your workflow to point to version 1.3 of this action to create review apps from forks
